

# DefaultController Routes

login:
  path: /login
  controller: App\Controller\DefaultController::login

index:
  path:     /
  controller: App\Controller\DefaultController::index

dashboard:
  path:     /dashboard
  controller: App\Controller\DefaultController::dashboard

editare:
  path:     /dashboard{id}
  controller: App\Controller\DefaultController::editare

logout:
  path: /logout


