

# DefaultController Routes

index:
  path:     /
  controller: App\Controller\DefaultController::index


projects:
  path:     /projects
  controller: App\Controller\DefaultController::projects


project:
  path:     /projects/{id}
  controller: App\Controller\DefaultController::project

press:
  path:     /press
  controller: App\Controller\DefaultController::pressMenu

agency:
  path:     /agency
  controller: App\Controller\DefaultController::agency

login:
  path:     /login
  controller: App\Controller\DefaultController::login

logout:
  path: /logout

contact:
  path:     /contact
  controller: App\Controller\DefaultController::contact

jobs:
  path:     /jobs
  controller: App\Controller\DefaultController::jobs

employee:
  path:     /employee
  controller: App\Controller\DefaultController::employee


dashboard:
  path:     /dashboard
  controller: App\Controller\DefaultController::dashboard

acceuil:
  path:     /dashboard/acceuil
  controller: App\Controller\DefaultController::acceuil

projectEdit:
  path:     /dashboard/project/{id}
  controller: App\Controller\DefaultController::projectEdit

categoryEdit:
  path:     /dashboard/category/{id}
  controller: App\Controller\DefaultController::categoryEdit

chiffreEdit:
  path:     /dashboard/chiffres/{id}
  controller: App\Controller\DefaultController::chiffreEdit